### ISSUE TITLE
Question about units for natural gas

### ISSUE THREAD

**Issue by efcaguab** [jagephart/FishPrint#2]
Just wanted to check the units for natural gas. In the `energy_carriers_impact_factors.csv` it appears that the impacts for natural gas as measured in kg CO2-eq  m^-3. However the column names in the LCA data suggest that natural gas use from the farms is measured in litres. 

I had a quick look at the code and saw the LCA data was converted in bases_03_ghg_model.R but I'm not sure this was done when calculating the stressors? 

Maybe the data is actually in cubic meters but the column name is incorrect?

**Comment by kdgorospe** [comment]
another good catch! you're right, we should be converting the energy impact factor for natural gas to Liters so that it fits the LCA data which is also in L. So yes, the bayes model does convert the natural gas impacts from m3 to L, but it doesn't look like this was done for any of the non-Bayesian workflows (i.e., wrangle_poultry_stressors.R, obs_level_01_calc_stressors.R, and scenarios_02_lever_analysis.R) which means all of those workflows will have to be re-estimated.

**Comment by kdgorospe** [comment]
UPDATE: The new impact factor for natural gas is 1.275 kg CO2-eq/L. The original value was 2.44 kg CO2-eq/m3. The new value assumes that at 15 C and one atmosphere the density of natural gas is 0.715 kg/m3 and the weight per kg is 0.41 kg/L. I'll reproduce all outputs that require this new value, while also removing all code that converts m3 to L as was done in the original code.
