### ISSUE TITLE
Monthly evaporative rates but annual yields

### ISSUE THREAD

**Issue by efcaguab** [jagephart/FishPrint#3]
Looking at the `clim_summarise_by_country.csv` file and the code that produced it in `evap_summarise.R` it appears that the values correspond to the monthly means rates per country (so effectively evaporation per month). 

However, the water stress is calculated as the inverse of yield (m^2 year / t) * grow out period yearly proportion * evaporative rate (m^3 / m^2 / month). Shouldn't the evaporative rates be calculated as the total per year (or multiplied by 12) for this to be valid?

**Comment by jagephart** [comment]
The average that we apply is the average evap rate across the year (so the average of the months). I think we left the monthly data in though because we wanted to leave the possibility of using the evap rate for particular months in the even that we knew which months were growing months. In the end, the grow out periods we could find were so close to a year that it wouldn't have made a difference.

**Comment by kdgorospe** [comment]
thanks for catching this Rahul. You're right! the evaporation data should be multiplied by 12 so that they're annual instead of monthly. I'll work on re-generating these estimates
